/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/

#include <stdint.h>

/**
 * Buffer going back to Dart
 * NOTE: must be freed with [embedded_milli_free_buffer] on the Dart side!
 */
typedef struct RustBuffer {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t capacity;
} RustBuffer;

/**
 * # Safety
 * Caller must ensure provided ptr and len point to a valid memory buffer.
 */
struct RustBuffer embedded_milli_process_instance_request(const uint8_t *ptr, uintptr_t len);

void embedded_milli_free_buffer(struct RustBuffer buffer);
