use std::env;

use cbindgen::Language;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    prost_build::compile_protos(&["proto/instance/request.proto"], &["proto"])
        .expect("Failed to run prost-build");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(Language::C)
        .with_autogen_warning(
            "/*
This file is automatically generated via build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/",
        )
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("bindings.h");
}
