[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.99"
prost = "0.14.1" # WARN: this must match what is currently in use by protoc-gen-prost
serde = "1.0.219"
serde_json = "1.0.143"
milli_v1 = { git = "https://github.com/meilisearch/meilisearch", package = "milli", tag = "v1.2.0" }

[build-dependencies]
cbindgen = "0.29.0"

[features]
default = ["milli_v1/all-tokenizations",]
# POSIX semaphores are needed for Apple's App Sandbox.
# Default LMDB uses SysV semaphores but App Sandbox disallows them.
# See https://github.com/GregoryConrad/mimir/issues/98
posix-sem = ["milli_v1/lmdb-posix-sem",]
