[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "=2.8.0"
anyhow = "1.0.*"
serde = "1.0.*"
serde_json = "1.0.*"
parking_lot = "0.12.*"
lazy_static = "1.*"
milli_v1 = { git = "https://github.com/meilisearch/meilisearch", package = "milli", tag = "v1.2.0" }

[features]
default = ["milli_v1/all-tokenizations",]
# POSIX semaphores are needed for Apple's App Sandbox.
# Default LMDB uses SysV semaphores but App Sandbox disallows them.
# See https://github.com/GregoryConrad/mimir/issues/98
posix-sem = ["milli_v1/lmdb-posix-sem",]
