import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [packageRoot.resolve('native/bindings.h')],
    ),
    functions: Functions.includeSet({
      'embedded_milli_process_instance_request',
      'embedded_milli_free_buffer',
    }),
    structs: Structs.includeSet({'RustBuffer', 'DartBuffer'}),
    output: Output(
      dartFile: packageRoot.resolve('lib/src/native/ffi.g.dart'),
      preamble: '''
// This file is automatically generated by ffigen.dart; DO NOT MANUALLY EDIT!

''',
    ),
  ).generate();
}
