import 'dart:io';

import 'package:ffigen/ffigen.dart';
import 'package:logging/logging.dart';

void main() {
  // NOTE: we want to get output for ffigen logs
  // ignore: avoid_print
  final logger = Logger('ffigen')..onRecord.listen(print);

  final packageRoot = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [packageRoot.resolve('native/bindings.h')],
    ),
    functions: Functions.includeSet({
      'embedded_milli_process_instance_request',
      'embedded_milli_free_buffer',
    }),
    structs: Structs.includeSet({'RustBuffer', 'DartBuffer'}),
    output: Output(
      dartFile: packageRoot.resolve('lib/src/native/ffi.g.dart'),
      preamble: '''
// This file is automatically generated by ffigen.dart; DO NOT MANUALLY EDIT!

''',
    ),
  ).generate(logger: logger);
}
