name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(deps): update nix flake.lock"
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
